In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("raw_data.csv")

In [3]:
df.head()

,userName,score,content,at,thumbsUpCount,source
0,Kayanat Anika,1,honestly i think there is a problem cuz i can'...,2026-03-12 23:21:40,0,ali-express_reviews
1,Nunya Biz,5,apparently when i set settings for notificatio...,2026-03-12 22:42:39,4,ali-express_reviews
2,Samarth Sandeep,1,this is by far the worst app i have bought 3 p...,2026-03-12 22:14:26,0,ali-express_reviews
3,Rubysu aka Natalie Debler,3,"my first package arrived, but with counterfeit...",2026-03-12 21:38:03,0,ali-express_reviews
4,Toni Dawn Moore,4,never shopped there yet,2026-03-12 21:24:39,0,ali-express_reviews

In [4]:
df = df[["score","content"]]

In [5]:
df.head()

   score                                            content
0      1  honestly i think there is a problem cuz i can'...
1      5  apparently when i set settings for notificatio...
2      1  this is by far the worst app i have bought 3 p...
3      3  my first package arrived, but with counterfeit...
4      4                            never shopped there yet

In [ ]:
# df.to_csv("raw_data.csv", index=False)

In [ ]:
# from transformers import pipeline

# # Load the classification pipeline with the specified model
# pipe = pipeline("text-classification", model="tabularisai/multilingual-sentiment-analysis")

# # Classify a new sentence
# sentence = "I love this product! It's amazing and works perfectly."
# result = pipe(sentence)

# # Print the result
# print(result)

In [ ]:
# import pandas as pd
# df = pd.read_csv('raw_data.csv')

# # 3. Define a function to get the label
# def get_sentiment(text):
#     if pd.isna(text) or text == "":
#         return "neutral"
#     # The model returns a list like: [{'label': 'Very Positive', 'score': 0.98}]
#     result = pipe(text)
#     return result[0]['label']

# # 4. Apply the model to the 'content' column and save to 'truthLabel'
# print("Processing records... this may take a moment.")
# df['truthLabel'] = df['content'].apply(get_sentiment)

# # 5. Save the updated file
# output_filename = "labeled_reviews_raw.csv"
# df.to_csv(output_filename, index=False)

# print(f"Done! File saved as {output_filename}")

# # Preview the results
# print(df[['content', 'truthLabel']].head())

In [7]:
df = pd.read_csv('labeled_reviews_raw.csv')

In [8]:
df.value_counts("truthLabel")

truthLabel
Negative    130
Positive     48
Neutral      22
Name: count, dtype: int64

In [4]:
df['truthLabel'] = df['truthLabel'].str.replace('Very Negative', 'Negative').replace('Very Positive', 'Positive')

In [5]:
df.value_counts("truthLabel")

truthLabel
Negative    130
Positive     48
Neutral      22
Name: count, dtype: int64

In [6]:
df.to_csv("labeled_reviews_raw.csv", index=False)